-- Stream/stream join to reproduce current behaviour
CREATE OR REPLACE STREAM S_LEGAL_ENTITY_1 (
    PrimaryCode VARCHAR KEY,
    LE_Name VARCHAR,
    LE_IS_OWNED_BY_LE VARCHAR,
    LE_IS_LOCATED_AT_CC VARCHAR
   ) WITH (
    KAFKA_TOPIC='LEGAL_ENTITY',
    PARTITIONS=1,
    VALUE_FORMAT='json'
   );

CREATE OR REPLACE STREAM S_LEGAL_ENTITY_2 (
    PrimaryCode VARCHAR KEY,
    LE_Name VARCHAR,
    LE_IS_OWNED_BY_LE VARCHAR,
    LE_IS_LOCATED_AT_CC VARCHAR
   ) WITH (
    KAFKA_TOPIC='LEGAL_ENTITY',
    PARTITIONS=1,
    VALUE_FORMAT='json'
   );

CREATE STREAM S_LEGAL_ENTITY_JOINT WITH (
    KAFKA_TOPIC='LEGAL_ENTITY_JOINT',
    PARTITIONS=1,
    VALUE_FORMAT='json')
  AS SELECT
    L1.PrimaryCode,
    L1.LE_IS_OWNED_BY_LE as UHC,
    L2.PrimaryCode,
    L2.LE_IS_OWNED_BY_LE
FROM S_LEGAL_ENTITY_1 L1 RIGHT JOIN S_LEGAL_ENTITY_2 L2 WITHIN 1 hour ON L1.PrimaryCode = L2.LE_IS_OWNED_BY_LE;

INSERT INTO S_LEGAL_ENTITY_1 (PrimaryCode, LE_Name, LE_IS_OWNED_BY_LE, LE_IS_LOCATED_AT_CC) VALUES ('LE_1143143','Penske Automotive Group, Inc.',null,'CC_159');
INSERT INTO S_LEGAL_ENTITY_1 (PrimaryCode, LE_Name, LE_IS_OWNED_BY_LE, LE_IS_LOCATED_AT_CC) VALUES ('LE_400058','Sytner Group Ltd','LE_1143143','CC_159');
INSERT INTO S_LEGAL_ENTITY_1 (PrimaryCode, LE_Name, LE_IS_OWNED_BY_LE, LE_IS_LOCATED_AT_CC) VALUES ('LE_400430','Ron Stratton (Knutsford) Limited','LE_400058','CC_159');
INSERT INTO S_LEGAL_ENTITY_1 (PrimaryCode, LE_Name, LE_IS_OWNED_BY_LE, LE_IS_LOCATED_AT_CC) VALUES ('LE_1143143','Penske Automotive Group, Inc.','','CC_159');

-- Table/table join example
CREATE OR REPLACE TABLE T_LEGAL_ENTITY_1 (
    PrimaryCode VARCHAR PRIMARY KEY,
    LE_Name VARCHAR,
    LE_IS_OWNED_BY_LE VARCHAR,
    LE_IS_LOCATED_AT_CC VARCHAR
   ) WITH (
    KAFKA_TOPIC='LEGAL_ENTITY_T',
    PARTITIONS=1,
    VALUE_FORMAT='json'
   );

CREATE OR REPLACE TABLE T_LEGAL_ENTITY_2 WITH (
    KAFKA_TOPIC='LEGAL_ENTITY_TT',
    PARTITIONS=1,
    VALUE_FORMAT='json',
    TIMESTAMP='SHIFTED_TS') AS
SELECT
      PRIMARYCODE,
      LE_Name,
      LE_IS_OWNED_BY_LE,
      LE_IS_LOCATED_AT_CC,
      rowtime + 1 as SHIFTED_TS
FROM T_LEGAL_ENTITY_1;

CREATE TABLE T_LEGAL_ENTITY_JOINT WITH (
    KAFKA_TOPIC='T_LEFAL_ENTITY_JOINT',
    PARTITIONS=1,
    VALUE_FORMAT='json')
  AS SELECT
    L1.PrimaryCode,
    L1.LE_Name as LE_Name,
    L1.LE_IS_OWNED_BY_LE as LE_Parent,
    CASE
      WHEN L2.LE_IS_OWNED_BY_LE = '' THEN L1.LE_IS_OWNED_BY_LE
      ELSE L2.LE_IS_OWNED_BY_LE
    END AS UHC
FROM T_LEGAL_ENTITY_1 L1 LEFT JOIN T_LEGAL_ENTITY_2 L2 ON L2.PrimaryCode = L1.LE_IS_OWNED_BY_LE;

INSERT INTO T_LEGAL_ENTITY_1 (PrimaryCode, LE_Name, LE_IS_OWNED_BY_LE, LE_IS_LOCATED_AT_CC) VALUES ('LE_1143143','Penske Automotive Group, Inc.','','CC_159');
INSERT INTO T_LEGAL_ENTITY_1 (PrimaryCode, LE_Name, LE_IS_OWNED_BY_LE, LE_IS_LOCATED_AT_CC) VALUES ('LE_400058','Sytner Group Ltd','LE_1143143','CC_159');
INSERT INTO T_LEGAL_ENTITY_1 (PrimaryCode, LE_Name, LE_IS_OWNED_BY_LE, LE_IS_LOCATED_AT_CC) VALUES ('LE_400430','Ron Stratton (Knutsford) Limited','LE_400058','CC_159');
INSERT INTO T_LEGAL_ENTITY_1 (PrimaryCode, LE_Name, LE_IS_OWNED_BY_LE, LE_IS_LOCATED_AT_CC) VALUES ('LE_400058','Sytner Group Ltd','LE_1143143_1','CC_159');
INSERT INTO T_LEGAL_ENTITY_1 (PrimaryCode, LE_Name, LE_IS_OWNED_BY_LE, LE_IS_LOCATED_AT_CC) VALUES ('LE_400430','Ron Stratton Limited','LE_400058_1','CC_159');
INSERT INTO T_LEGAL_ENTITY_1 (PrimaryCode, LE_Name, LE_IS_OWNED_BY_LE, LE_IS_LOCATED_AT_CC) VALUES ('LE_400058_1','Ron Stratton 1 Limited','LE_1143143_1','CC_159');
